name: Jekyll site CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: store git hash for site generation
      run: 'echo "commitid: $GITHUB_SHA" > _config-github.yml'
    - name: Build site
      shell: 'script -q -e -c "bash {0}"'
      run: ./docker_jekyll_build.sh
    - name: rsync deployment
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -rv --delete
        path: _site/
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
        