name: Jekyll site CI

on:
  push:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build site
      shell: 'script -q -e -c "bash {0}"'
      run: ./docker_jekyll_build.sh
        